//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class App
    {
        public static readonly string MenuItemExitHeader = "Localization.App.MenuItemExitHeader";
        public static readonly string MenuItemOpenMainWindowHeader = "Localization.App.MenuItemOpenMainWindowHeader";
    }
}
namespace Localization.Controls
{
    public static class ChatEdit
    {
        public static readonly string Title = "Localization.Controls.ChatEdit.Title";
        public static readonly string OkButtonContent = "Localization.Controls.ChatEdit.OkButtonContent";
        public static readonly string CancelButtonContent = "Localization.Controls.ChatEdit.CancelButtonContent";
    }
}
namespace Localization.Controls
{
    public static class ChatInput
    {
        public static readonly string Submit = "Localization.Controls.ChatInput.Submit";
        public static readonly string ErrorNotificationTitle = "Localization.Controls.ChatInput.ErrorNotificationTitle";
        public static readonly string ChoiceFileTitle = "Localization.Controls.ChatInput.ChoiceFileTitle";
    }
}
namespace Localization.Controls
{
    public static class ChatRender
    {
        public static readonly string ExecutePluginLabel = "Localization.Controls.ChatRender.ExecutePluginLabel";
        public static readonly string ParamLabel = "Localization.Controls.ChatRender.ParamLabel";
        public static readonly string DeleteButtonTip = "Localization.Controls.ChatRender.DeleteButtonTip";
        public static readonly string CopyButtonTip = "Localization.Controls.ChatRender.CopyButtonTip";
        public static readonly string EditButtonTip = "Localization.Controls.ChatRender.EditButtonTip";
        public static readonly string ReGenerateTip = "Localization.Controls.ChatRender.ReGenerateTip";
        public static readonly string CopyButonContent = "Localization.Controls.ChatRender.CopyButonContent";
        public static readonly string CopySuccessNotificationTitle = "Localization.Controls.ChatRender.CopySuccessNotificationTitle";
        public static readonly string CopySuccessNotificationMessage = "Localization.Controls.ChatRender.CopySuccessNotificationMessage";
        public static readonly string ApplyButtonContent = "Localization.Controls.ChatRender.ApplyButtonContent";
        public static readonly string ApplyDoing = "Localization.Controls.ChatRender.ApplyDoing";
        public static readonly string ApplyComplete = "Localization.Controls.ChatRender.ApplyComplete";
        public static readonly string ApplyFail = "Localization.Controls.ChatRender.ApplyFail";
        public static readonly string ApplyFailMessage = "Localization.Controls.ChatRender.ApplyFailMessage";
    }
}
namespace Localization.Controls
{
    public static class ChatWelcome
    {
        public static readonly string WelcomeContent = "Localization.Controls.ChatWelcome.WelcomeContent";
    }
}
namespace Localization.Controls
{
    public static class WorkspaceConversation
    {
        public static readonly string CopyNotificationTitle = "Localization.Controls.WorkspaceConversation.CopyNotificationTitle";
        public static readonly string CopyNotificationMessage = "Localization.Controls.WorkspaceConversation.CopyNotificationMessage";
        public static readonly string ErrorNotificationTitle = "Localization.Controls.WorkspaceConversation.ErrorNotificationTitle";
    }
}
namespace Localization.Controls
{
    public static class WorkspaceHeader
    {
        public static readonly string HideButtonTip = "Localization.Controls.WorkspaceHeader.HideButtonTip";
    }
}
namespace Localization.Pages
{
    public static class Setting
    {
        public static readonly string Title = "Localization.Pages.Setting.Title";
        public static readonly string MaxTokenLabel = "Localization.Pages.Setting.MaxTokenLabel";
        public static readonly string LanguageKey = "Localization.Pages.Setting.LanguageKey";
        public static readonly string LanguagePlaceholderText = "Localization.Pages.Setting.LanguagePlaceholderText";
        public static readonly string SaveButtonContent = "Localization.Pages.Setting.SaveButtonContent";
        public static readonly string SaveSuccessNotificationTitle = "Localization.Pages.Setting.SaveSuccessNotificationTitle";
        public static readonly string SaveSuccessNotificationMessage = "Localization.Pages.Setting.SaveSuccessNotificationMessage";
    }
}
namespace Localization.Pages
{
    public static class Tool
    {
        public static readonly string TranslateLabel = "Localization.Pages.Tool.TranslateLabel";
        public static readonly string TranslateWatermark = "Localization.Pages.Tool.TranslateWatermark";
    }
}
namespace Localization.Views
{
    public static class MainView
    {
        public static readonly string NavItemChatContent = "Localization.Views.MainView.NavItemChatContent";
        public static readonly string NavItemToolContent = "Localization.Views.MainView.NavItemToolContent";
        public static readonly string NeedLoginText = "Localization.Views.MainView.NeedLoginText";
        public static readonly string LoginButtonContent = "Localization.Views.MainView.LoginButtonContent";
        public static readonly string loginSuccessNotificationTitle = "Localization.Views.MainView.loginSuccessNotificationTitle";
        public static readonly string loginSuccessNotificationMessage = "Localization.Views.MainView.loginSuccessNotificationMessage";
    }
}
namespace Localization.Views
{
    public static class MainWindow
    {
        public static readonly string Title = "Localization.Views.MainWindow.Title";
    }
}
